# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 2
# RUN: llc --verify-machineinstrs -mtriple=aarch64 -o - %s -run-pass pipeliner -aarch64-enable-pipeliner -pipeliner-mve-cg -mcpu=neoverse-n1 -pipeliner-force-ii=3 | FileCheck %s

# Large counter subtraction immediate
---
name:            test
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
  ; CHECK-NEXT:   [[FMOVD0_:%[0-9]+]]:fpr64 = FMOVD0
  ; CHECK-NEXT:   [[FMOVDi:%[0-9]+]]:fpr64 = FMOVDi 8
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVZXi:%[0-9]+]]:gpr64 = MOVZXi 2, 0
  ; CHECK-NEXT:   [[MOVZXi1:%[0-9]+]]:gpr64 = MOVZXi 4000, 0
  ; CHECK-NEXT:   [[MADDXrrr:%[0-9]+]]:gpr64 = MADDXrrr [[MOVZXi]], [[MOVZXi1]], $xzr
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY [[COPY]]
  ; CHECK-NEXT:   dead $xzr = SUBSXrs [[COPY1]], [[MADDXrrr]], 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.4, implicit $nzcv
  ; CHECK-NEXT:   B %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUBSXri:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY]], 4000, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FMADDDrrr:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64all = COPY [[SUBSXri]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64all = PHI %19, %bb.5, [[COPY]], %bb.4
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr64 = PHI %21, %bb.5, [[SUBSXri]], %bb.4
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:fpr64 = PHI %23, %bb.5, [[FMADDDrrr]], %bb.4
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fpr64 = PHI %25, %bb.5, [[FMOVD0_]], %bb.4
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:gpr64sp = PHI %27, %bb.5, [[COPY2]], %bb.4
  ; CHECK-NEXT:   [[SUBSXri1:%[0-9]+]]:gpr64 = nsw SUBSXri [[PHI4]], 4000, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FMADDDrrr1:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI3]], [[PHI2]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr64sp = COPY [[SUBSXri1]]
  ; CHECK-NEXT:   [[SUBSXri2:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY3]], 4000, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FMADDDrrr2:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr1:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr]], [[FMADDDrrr1]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr64all = COPY [[SUBSXri2]]
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr64sp = COPY [[SUBSXri2]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY5]], 4000, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.5, implicit $nzcv
  ; CHECK-NEXT:   B %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.7(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[FADDDrr2:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr1]], [[FMADDDrrr2]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr64sp = COPY [[SUBSXri2]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY6]], 0, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.7, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI5:%[0-9]+]]:gpr64sp = PHI [[COPY]], %bb.3, [[COPY4]], %bb.6
  ; CHECK-NEXT:   [[PHI6:%[0-9]+]]:fpr64 = PHI [[FMOVD0_]], %bb.3, [[FADDDrr2]], %bb.6
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI7:%[0-9]+]]:gpr64sp = PHI [[PHI5]], %bb.7, %4, %bb.1
  ; CHECK-NEXT:   [[PHI8:%[0-9]+]]:fpr64 = PHI [[PHI6]], %bb.7, %6, %bb.1
  ; CHECK-NEXT:   [[FMADDDrrr3:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr3:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI8]], [[FMADDDrrr3]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri3:%[0-9]+]]:gpr64 = nsw SUBSXri [[PHI7]], 4000, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr64all = COPY [[SUBSXri3]]
  ; CHECK-NEXT:   Bcc 0, %bb.2, implicit $nzcv
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PHI9:%[0-9]+]]:fpr64 = PHI [[FADDDrr3]], %bb.1, [[FADDDrr2]], %bb.6
  ; CHECK-NEXT:   $d0 = COPY [[PHI9]]
  ; CHECK-NEXT:   RET_ReallyLR implicit $d0
  bb.0:
    liveins: $x0

    %0:gpr64all = COPY $x0
    %13:fpr64 = FMOVD0
    %17:fpr64 = FMOVDi 8
    B %bb.1

  bb.1:
    %2:gpr64sp = PHI %0, %bb.0, %7, %bb.1
    %4:fpr64 = PHI %13, %bb.0, %5, %bb.1
    %22:fpr64 = nofpexcept FMADDDrrr %17, %17, %17, implicit $fpcr
    %5:fpr64 = nofpexcept FADDDrr %4, killed %22, implicit $fpcr
    %23:gpr64 = nsw SUBSXri %2, 4000, 0, implicit-def $nzcv
    %7:gpr64all = COPY %23
    Bcc 0, %bb.2, implicit $nzcv
    B %bb.1

  bb.2:
    $d0 = COPY %5
    RET_ReallyLR implicit $d0
...
