# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 2
# RUN: llc --verify-machineinstrs -mtriple=aarch64 -o - %s -run-pass pipeliner -aarch64-enable-pipeliner -pipeliner-mve-cg -mcpu=neoverse-n1 -pipeliner-force-ii=4 | FileCheck %s
# #Unroll > #Stages
---
name:            test
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
  ; CHECK-NEXT:   [[FMOVD0_:%[0-9]+]]:fpr64 = FMOVD0
  ; CHECK-NEXT:   [[FMOVDi:%[0-9]+]]:fpr64 = FMOVDi 8
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64sp = COPY [[COPY]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.4, implicit $nzcv
  ; CHECK-NEXT:   B %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUBSXri:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FMADDDrrr:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64all = COPY [[SUBSXri]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:fpr64 = PHI %22, %bb.5, [[FMOVD0_]], %bb.4
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr64all = PHI %24, %bb.5, [[COPY]], %bb.4
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr64 = PHI %28, %bb.5, [[SUBSXri]], %bb.4
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:fpr64 = PHI %30, %bb.5, [[FMADDDrrr]], %bb.4
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:gpr64sp = PHI %33, %bb.5, [[COPY2]], %bb.4
  ; CHECK-NEXT:   [[PHI5:%[0-9]+]]:fpr64 = PHI %36, %bb.5, [[FMOVD0_]], %bb.4
  ; CHECK-NEXT:   [[FADDDrr:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI5]], [[PHI3]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri1:%[0-9]+]]:gpr64 = nsw SUBSXri [[PHI4]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FMADDDrrr1:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr64sp = COPY [[SUBSXri1]]
  ; CHECK-NEXT:   [[FADDDrr1:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr]], [[PHI]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr2:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr1]], [[FMADDDrrr1]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri2:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY3]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FMADDDrrr2:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr64sp = COPY [[SUBSXri2]]
  ; CHECK-NEXT:   [[FADDDrr3:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr2]], [[PHI3]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr4:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr3]], [[FMADDDrrr2]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri3:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY4]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FMADDDrrr3:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr64all = COPY [[SUBSXri3]]
  ; CHECK-NEXT:   [[FADDDrr5:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr4]], [[FMADDDrrr1]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr64sp = COPY [[SUBSXri3]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY6]], 2, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.5, implicit $nzcv
  ; CHECK-NEXT:   B %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.7(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[FADDDrr6:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr5]], [[FMADDDrrr3]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr7:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr6]], [[FMADDDrrr2]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr64sp = COPY [[SUBSXri3]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY7]], 0, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.7, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI6:%[0-9]+]]:fpr64 = PHI [[FMOVD0_]], %bb.3, [[FMADDDrrr3]], %bb.6
  ; CHECK-NEXT:   [[PHI7:%[0-9]+]]:gpr64sp = PHI [[COPY]], %bb.3, [[COPY5]], %bb.6
  ; CHECK-NEXT:   [[PHI8:%[0-9]+]]:fpr64 = PHI [[FMOVD0_]], %bb.3, [[FADDDrr7]], %bb.6
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI9:%[0-9]+]]:gpr64sp = PHI [[PHI7]], %bb.7, %4, %bb.1
  ; CHECK-NEXT:   [[PHI10:%[0-9]+]]:fpr64 = PHI [[PHI8]], %bb.7, %6, %bb.1
  ; CHECK-NEXT:   [[PHI11:%[0-9]+]]:fpr64 = PHI [[PHI6]], %bb.7, %8, %bb.1
  ; CHECK-NEXT:   [[FMADDDrrr4:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr8:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI10]], [[FMADDDrrr4]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr9:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr8]], [[PHI11]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri4:%[0-9]+]]:gpr64 = nsw SUBSXri [[PHI9]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:gpr64all = COPY [[SUBSXri4]]
  ; CHECK-NEXT:   Bcc 0, %bb.2, implicit $nzcv
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PHI12:%[0-9]+]]:fpr64 = PHI [[FADDDrr9]], %bb.1, [[FADDDrr7]], %bb.6
  ; CHECK-NEXT:   $d0 = COPY [[PHI12]]
  ; CHECK-NEXT:   RET_ReallyLR implicit $d0
  bb.0:
    liveins: $x0

    %0:gpr64all = COPY $x0
    %13:fpr64 = FMOVD0
    %17:fpr64 = FMOVDi 8
    B %bb.1

  bb.1:
    %2:gpr64sp = PHI %0, %bb.0, %7, %bb.1
    %4:fpr64 = PHI %13, %bb.0, %6, %bb.1
    %24:fpr64 = PHI %13, %bb.0, %22, %bb.1
    %22:fpr64 = nofpexcept FMADDDrrr %17, %17, %17, implicit $fpcr
    %5:fpr64 = nofpexcept FADDDrr %4, %22, implicit $fpcr
    %6:fpr64 = nofpexcept FADDDrr %5, %24, implicit $fpcr
    %23:gpr64 = nsw SUBSXri %2, 1, 0, implicit-def $nzcv
    %7:gpr64all = COPY %23
    Bcc 0, %bb.2, implicit $nzcv
    B %bb.1

  bb.2:
    $d0 = COPY %6
    RET_ReallyLR implicit $d0
...
