# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 2
# RUN: llc --verify-machineinstrs -mtriple=aarch64 -o - %s -run-pass pipeliner -aarch64-enable-pipeliner -pipeliner-mve-cg -mcpu=neoverse-n1 -pipeliner-force-ii=3 | FileCheck %s

# Last definitions are in kernel and epilog blocks
---
name:            test
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT:   liveins: $x0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr64sp = COPY $x0
  ; CHECK-NEXT:   [[FMOVD0_:%[0-9]+]]:fpr64 = FMOVD0
  ; CHECK-NEXT:   [[FMOVDi:%[0-9]+]]:fpr64 = FMOVDi 8
  ; CHECK-NEXT:   B %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr64sp = COPY [[COPY]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY1]], 3, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.4, implicit $nzcv
  ; CHECK-NEXT:   B %bb.7
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SUBSXri:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FADDDrr:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FMADDDrrr:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr64sp = COPY [[SUBSXri]]
  ; CHECK-NEXT:   [[SUBSXri1:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY2]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FADDDrr1:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FMADDDrrr1:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr64all = COPY [[SUBSXri1]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr64 = PHI %22, %bb.5, [[SUBSXri]], %bb.4
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:fpr64 = PHI %24, %bb.5, [[FADDDrr]], %bb.4
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:fpr64 = PHI %26, %bb.5, [[FMADDDrrr]], %bb.4
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:gpr64all = PHI %28, %bb.5, [[COPY2]], %bb.4
  ; CHECK-NEXT:   [[PHI4:%[0-9]+]]:fpr64 = PHI %30, %bb.5, [[FMOVD0_]], %bb.4
  ; CHECK-NEXT:   [[PHI5:%[0-9]+]]:gpr64 = PHI %32, %bb.5, [[SUBSXri1]], %bb.4
  ; CHECK-NEXT:   [[PHI6:%[0-9]+]]:fpr64 = PHI %34, %bb.5, [[FADDDrr1]], %bb.4
  ; CHECK-NEXT:   [[PHI7:%[0-9]+]]:fpr64 = PHI %38, %bb.5, [[FMADDDrrr1]], %bb.4
  ; CHECK-NEXT:   [[PHI8:%[0-9]+]]:gpr64sp = PHI %41, %bb.5, [[COPY3]], %bb.4
  ; CHECK-NEXT:   [[FADDDrr2:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI2]], [[PHI4]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri2:%[0-9]+]]:gpr64 = nsw SUBSXri [[PHI8]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FADDDrr3:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI6]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FMADDDrrr2:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr64sp = COPY [[SUBSXri2]]
  ; CHECK-NEXT:   [[FADDDrr4:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI7]], [[FADDDrr2]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri3:%[0-9]+]]:gpr64 = nsw SUBSXri [[COPY4]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[FADDDrr5:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FADDDrr3]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FMADDDrrr3:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr64all = COPY [[SUBSXri3]]
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gpr64sp = COPY [[SUBSXri3]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY6]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.5, implicit $nzcv
  ; CHECK-NEXT:   B %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.7(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[FADDDrr6:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FMADDDrrr2]], [[FADDDrr4]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr7:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FMADDDrrr3]], [[FADDDrr6]], implicit $fpcr
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gpr64sp = COPY [[SUBSXri3]]
  ; CHECK-NEXT:   dead $xzr = SUBSXri [[COPY7]], 0, 0, implicit-def $nzcv
  ; CHECK-NEXT:   Bcc 12, %bb.7, implicit $nzcv
  ; CHECK-NEXT:   B %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI9:%[0-9]+]]:fpr64 = PHI [[FMOVDi]], %bb.3, [[FADDDrr5]], %bb.6
  ; CHECK-NEXT:   [[PHI10:%[0-9]+]]:fpr64 = PHI [[FMOVD0_]], %bb.3, [[FMADDDrrr3]], %bb.6
  ; CHECK-NEXT:   [[PHI11:%[0-9]+]]:gpr64sp = PHI [[COPY]], %bb.3, [[COPY5]], %bb.6
  ; CHECK-NEXT:   [[PHI12:%[0-9]+]]:fpr64 = PHI [[FMOVD0_]], %bb.3, [[FADDDrr7]], %bb.6
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI13:%[0-9]+]]:gpr64sp = PHI [[PHI11]], %bb.7, %4, %bb.1
  ; CHECK-NEXT:   [[PHI14:%[0-9]+]]:fpr64 = PHI [[PHI12]], %bb.7, %6, %bb.1
  ; CHECK-NEXT:   [[PHI15:%[0-9]+]]:fpr64 = PHI [[PHI9]], %bb.7, %8, %bb.1
  ; CHECK-NEXT:   dead [[PHI16:%[0-9]+]]:fpr64 = PHI [[PHI10]], %bb.7, %10, %bb.1
  ; CHECK-NEXT:   [[FMADDDrrr4:%[0-9]+]]:fpr64 = nofpexcept FMADDDrrr [[FMOVDi]], [[FMOVDi]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr8:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[PHI15]], [[FMOVDi]], implicit $fpcr
  ; CHECK-NEXT:   [[FADDDrr9:%[0-9]+]]:fpr64 = nofpexcept FADDDrr [[FMADDDrrr4]], [[PHI14]], implicit $fpcr
  ; CHECK-NEXT:   [[SUBSXri4:%[0-9]+]]:gpr64 = nsw SUBSXri [[PHI13]], 1, 0, implicit-def $nzcv
  ; CHECK-NEXT:   [[COPY8:%[0-9]+]]:gpr64all = COPY [[SUBSXri4]]
  ; CHECK-NEXT:   Bcc 0, %bb.2, implicit $nzcv
  ; CHECK-NEXT:   B %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   [[PHI17:%[0-9]+]]:fpr64 = PHI [[FADDDrr8]], %bb.1, [[FADDDrr5]], %bb.6
  ; CHECK-NEXT:   [[PHI18:%[0-9]+]]:fpr64 = PHI [[FADDDrr9]], %bb.1, [[FADDDrr7]], %bb.6
  ; CHECK-NEXT:   $d0 = COPY [[PHI17]]
  ; CHECK-NEXT:   $d0 = nofpexcept FADDDrr $d0, [[PHI18]], implicit $fpcr
  ; CHECK-NEXT:   RET_ReallyLR implicit $d0
  bb.0:
    liveins: $x0

    %0:gpr64all = COPY $x0
    %13:fpr64 = FMOVD0
    %17:fpr64 = FMOVDi 8
    B %bb.1

  bb.1:
    %2:gpr64sp = PHI %0, %bb.0, %7, %bb.1
    %4:fpr64 = PHI %13, %bb.0, %6, %bb.1
    %25:fpr64 = PHI %17, %bb.0, %5, %bb.1
    %24:fpr64 = PHI %13, %bb.0, %22, %bb.1
    %22:fpr64 = nofpexcept FMADDDrrr %17, %17, %17, implicit $fpcr
    %5:fpr64 = nofpexcept FADDDrr %25, %17, implicit $fpcr
    %6:fpr64 = nofpexcept FADDDrr %22, %4, implicit $fpcr
    %23:gpr64 = nsw SUBSXri %2, 1, 0, implicit-def $nzcv
    %7:gpr64all = COPY %23
    Bcc 0, %bb.2, implicit $nzcv
    B %bb.1

  bb.2:
    $d0 = COPY %5
    $d0 = nofpexcept FADDDrr $d0, %6, implicit $fpcr
    RET_ReallyLR implicit $d0
...
